# blank_issues_enabled: false
# contact_links:
#   - name: Join nf-core
#     url: https://nf-co.re/join
#     about: Please join the nf-core community here
#   - name: "Slack #stringstats channel"
#     url: https://nfcore.slack.com/channels/stringstats
#     about: Discussion about the nf-core/stringstats pipeline
